export const URL = {
  // BASE_URL: 'http://18.140.237.139:3100',
  BASE_URL: 'http://wshejob.adaptivebizapp.com:3100',
  BASE_URL_SBS: 'http://wshejob.adaptivebizapp.com:3200',
  BASE_URL_Link3: 'http://wshejob.adaptivebizapp.com:3300',
  BASE_URL_Link4: 'http://wshejob.adaptivebizapp.com:3400',
  BASE_URL_Link5: 'http://wshejob.adaptivebizapp.com:3500',
  BASE_URL_Link6: 'http://wshejob.adaptivebizapp.com:3600',
  BASE_URL_Link7: 'http://wshejob.adaptivebizapp.com:3700',
  BASE_URL_Link8: 'https://wshapp.adaptivebizapp.com',
  BASE_URL_Link8_REPORT: 'https://wsh.adaptivebizapp.com',
  BASE_URL_Link8_DEV: 'https://dev1.adaptivebizapp.com/pcmapp',
  BASE_URL_Link8_DEV_REPORT: 'https://dev1.adaptivebizapp.com/pcm',

  // BASE_URL: 'http://13.127.201.108:3100'
  // BASE_URL: "http://54.255.237.156:3100",

  login: '/api/login',
  loginV2: '/Token',
  changePassword: '/api/changepassword',
  getUserByUserName: '/api/getUserByUserName',
  getClockInAndOutStatus: '/api/getClockInAndOutStatus',
  getUpcomingSchedule: '/api/getUpcomingSchedule',
  checkIn: '/api/checkIn',
  checkOut: '/api/checkOut',
  applyLeave: '/api/applyLeave',
  getAllTaskTypeMaster: '/api/getAllTaskTypeMaster',
  taskByEmployees: '/api/taskByEmployees',
  getTaskByEmployee: '/api/getTaskByEmployee',
  locationTracking: '/api/locationTracking',
  getEmployeesForshiftAndLocations: '/api/getEmployeesForshiftAndLocations',
  locationsForSupervisorCurrent: '/api/locationsForSupervisorCurrent',
  auditBySupervisor: '/api/auditBySupervisor',
  getEmployeesLeaveForSupervisor: '/api/getEmployeesLeaveForSupervisor',
  getUnassignedEmployeeByScheduleId: '/api/getUnassignedEmployeeByScheduleId',
  shiftsForSupervisorCurrent: '/api/shiftsForSupervisorCurrent',
  assignSupervisorItself: '/api/assignSupervisorItself',
  assignBySupervisor: '/api/assignBySupervisor',
  getReportUrl: '/api/getReportUrl',
  getMobileReportUrl: '/api/GetMobileLinks',
  getMobileReportList: '/api/GetMobileReportDropdowns',
  getAuditsSupervisor: '/api/getAuditsSupervisor',
  auditsBysupervisorForClients: '/api/auditsBysupervisorForClients',
  scheduleForClients: '/api/scheduleForClients',
  getLocationsForEmp: '/api/getLocationsForEmp',
  postMobileReport: '/api/postMobileReport',
  getMobileReport: '/api/getMobileReport',
  getAttandance: '/api/getAttendanceForEmp',
  getDashboardAttendance: '/api/dashBoard',
  getSpringCleaning: '/api/getSprinkCleanDates',
  getLeaveList: '/api/V2/GetLeavelist'
};

export const Colors = {
  white: '#ffff',
  black: '#000',
  transparent: 'transparent',
  green: 'green',
  orange: 'orange',
  success: '#4CCC4C',
  darkBlack: '#0F0E0E',
  lightBlack: '#0F0E0E',
  logo: '#FF2E2E',
  yellow: 'yellow',
  grey: '#CCC',
  red: 'red',
};

export const Labels = {
  userName: 'Username',
  password: 'Password',
  newPassword: 'New Password',
  none: 'none',
  login: 'LOG IN',
  clock: 'Clock In & Clock Out',
  clockIn: 'Clock In',
  clockOut: 'Clock Out',
  projectPlace: 'Project Location',
  place: 'velacherry',
  shiftTiming: 'Shift Timing',
  timing: '12:00 AM to 10:00 PM',
  schedule: 'Upcoming Schedules',
  applyLeave: 'Apply Leave',
  task: 'Task',
  addTask: 'Add Task',
  cpassword: 'Confirm Password',
  changePassword: 'Change Password',
  changePasswordLink: 'Change Password?',
  loginLink: 'Back to Login?',
  Employees: 'Employees',
  Audit: 'Audit',
  Dashboard: 'Dashboard',
  Link: 'Link',
  AuditView: 'Audit View',
  ScheduleView: 'Schedule View',
  AttendanceDetail: 'Attendance View',
  AttendanceDashboard: 'Dashboard Attendance',
  ReportsView: 'View Reports',
  SpringCleaning: 'Spring Cleaning Days'
};

export const ScreenName = {
  landing: 'Landing',
  login: 'Login',
  clock: 'Clock',
  schedule: 'Schedule',
  task: 'Task',
  addTask: 'Add Task',
  changePassword: 'Change Password',
  Employees: 'Employees',
  Audit: 'Audit',
  Reassign: 'Reassign',
  Dashboard: 'Dashboard',
  AttendanceDashboard: 'AttendanceDashboard',
  Link: 'Link',
  addAudit: 'Add Audit',
  AuditView: 'Audit View',
  ScheduleView: 'Schedule View',
  Reports: 'Reports',
  ReportsView: 'View Reports',
  ViewReport: 'Report View',
  AttendanceDetail: 'Attendance View',
  SpringCleaning: 'Spring Cleaning',

  // NEW API SCREEN
  ClockV2: 'ClockV2',
  AttendanceDetailV2: 'Attendance ViewV2',
  scheduleV2: 'ScheduleV2',
  LinkV2: 'LinkV2',
  ReportsV2: 'ReportsV2',
};

export const Icons = {
  arrowback: 'arrow-back',
  logout: 'logout',
  location: 'location-pin',
  phone: 'phone',
  menu: 'menu',
  map: 'map',
  antDesign: 'AntDesign',
  entypo: 'Entypo',
  MaterialIcons: 'MaterialIcons',
  SimpleLineIcons: 'SimpleLineIcons',
  Ionicons: 'Ionicons',
  MaterialCommunityIcons: 'MaterialCommunityIcons',
  FontAwesome: 'FontAwesome',
  EvilIcons: 'EvilIcons',
  arrowBack: 'arrow-back'
};

export const roles = {
  0: 'Empty',
  1: 'Client',
  2: 'Supervisor',
  3: 'Employee',
};

export const privileges = {
  0: [],
  1: [
    'Dashboard',
    'AttendanceDashboard',
    'View Reports',
    'Login',
    'Link',
    'Audit View',
    'Schedule View',
    'Spring Cleaning'
  ],
  2: [
    'Dashboard',
    'AttendanceDashboard',
    'Employees',
    'Audit',
    'Reassign',
    'Link',
    'Schedule View',
    'View Reports',
    'Login',
    'Spring Cleaning'
  ],
  3: [
    'Dashboard',
    'Clock',
    'Reports',
    'Schedule',
    'Task',
    'Add Task',
    'Link',
    'Login',
    'Attendance View'
  ],
};
