export const ADD_TASKS = 'ADD_TASKS';
export const UPDATE_TASKS = 'UPDATE_TASKS';
export const ADD_NEW_TASKS_BY_EMPLOYEES = 'ADD_NEW_TASKS_BY_EMPLOYEES';
export const GET_TASK_BY_EMPLOYEES = 'GET_TASK_BY_EMPLOYEES';
export const UPDATE_TASK_TYPES = 'UPDATE_TASK_TYPES';
